
sudo: false
language: python
python:
- '3.6'
env:
  global:
  - PACKAGE_NAME=tunga
before_install:
  - export BUILD_VERSION=$(date "+%Y%m%d").$TRAVIS_BUILD_NUMBER
  - export PACKAGE_NAME_VERSION=$PACKAGE_NAME.$BUILD_VERSION
script:
  - python setup.py sdist bdist_wheel
  - pip install .
  - pip install -r requirements.txt
deploy:
  provider: pypi
  user: "__token__"
  distributions: sdist bdist_wheel
  password:
    secure: "NDoO5Bx6YEWrd4QZCZhZY7dYPfkVlSjyt7XhFMMHQ5yqVB9S9P8RSn4UtKKn92AxAJv5mIrAAoe2Rb92ChNqpGCUyAg868IRC8NkyGleam68+ZfClow8OD11BQriuH6YVbT2tr4jWqr+As1hLOV0Gt5aCtDHScRQhTW8o3YXCyk4jSxrr8K19NYamvfccsRvkhivhKsCUKPq1TLk5gzLOd/y4Mj5Ufn+4h/J4C8su6rIWYkacWMTYDRJ1Y9aJK4gjBTYL/zmigUDmybB+1SnyxK3jvfzoIblB3UTIrW+uE0xD4D3nttPnQxlVKCZKjIbjMD8sSolNzSSY9XYTtWue3sCre23VODLCIfCO1qyYXGpnIdh/hfsYcTe8FLocNJVGXxAMSLPIfQZMd7SR6Y5gU76cEzNQeiyN7s5AJUDpVl+s4ccYjWtGOdHI3rAQV9KuF66vCMJFl3C11koAOm3BWdf3vGD8KqMRtEsolXQi3WPgFaGEi8MnDDP4huPuQ90Gqwb1TavqVMnEqH7+/9slm3NrLWC6tU3TZBBpntfxO0P4wALwaucg0nt+e0k7XWoEp5bSubnbak1bNWywB9OSfEjPylKABSDZHPWuGKIfnlwUD6rN/2cvBhCLenODz+hiFWs9CY3xolxrvEAH/eX7rpJd5cx+ifLjVuRA8Ln2bk="
  skip_cleanup: true
  skip_existing: true
notifications:
  email:
  - tahtaciburak@gmail.com