
sudo: false
language: python
python:
- '3.6'
env:
  global:
  - PACKAGE_NAME=tunga
before_install:
  - export BUILD_VERSION=$(date "+%Y%m%d").$TRAVIS_BUILD_NUMBER
  - export PACKAGE_NAME_VERSION=$PACKAGE_NAME.$BUILD_VERSION
script:
  - python setup.py sdist bdist_wheel
  - pip install .
  - pip install -r requirements.txt
deploy:
  provider: pypi
  user: "__token__"
  distributions: sdist bdist_wheel
  password:
    secure: "AgEIcHlwaS5vcmcCJGFmODBkYzhkLTExZTktNDJhZi1iYTE4LTRkMTlmNjExMmI2OAACNnsicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJ0dW5nYSJdfSwgInZlcnNpb24iOiAxfQAABiAd5R-5RdACstXm8RXVXCBeXDZ1jA4YlIVFUmWPQEa7JA"
  skip_cleanup: true
  skip_existing: true
notifications:
  email:
  - tahtaciburak@gmail.com